apps/cart/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .paypal_views import paypal_form
from .views import (Step0View, Step2View, Step3View, UpdateCartView, CartAjaxView,
                    YooKassaWebhookView, YooKassaCartView, PayPalWebhookView, PayPalCartView, RoboKassaCartView, RoboKassaSuccessView, RoboKassaFailView)


urlpatterns = [
    url(r'^steps/0/$', Step0View.as_view(), name='step0'),
    url(r'^steps/2/$', Step2View.as_view(), name='step2'),
    url(r'^steps/3/$', Step3View.as_view(), name='step3'),

    url(r'^update/$', UpdateCartView.as_view(), name='update'),

    url(r'^set/$', CartAjaxView.as_view(action='set'), name='set'),
    url(r'^remove/$', CartAjaxView.as_view(action='remove'), name='remove'),
    url(r'^clear/$', CartAjaxView.as_view(action='clear'), name='clear'),

    # yookassa
    url(r'^yookassa/webhook/$', YooKassaWebhookView.as_view(), name='yookassa_webhook'),
    url(r'^yookassa/(?P<pk>\d+)/$', YooKassaCartView.as_view(), name='yookassa'),

    # paypal
    url(r'^paypal/webhook/$', PayPalWebhookView.as_view(), name='paypal_webhook'),
    url(r'^paypal/(?P<pk>\d+)/$', PayPalCartView.as_view(), name='paypal'),
    url(r'^paypal/form/$', paypal_form, name='paypal_form'),

    # robokassa
    url(r'^robokassa/result/$', RoboKassaCartView.as_view(), name='robokassa'),
    url(r'^robokassa/success/$', RoboKassaSuccessView.as_view(), name='robokassa_success'),
    url(r'^robokassa/fail/$', RoboKassaFailView.as_view(), name='robokassa_fail'),

]

apps/cart/certificate/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import CertificateCartSetView, CertificateCartRemoveView


urlpatterns = [
    url(r'^set/$', CertificateCartSetView.as_view(), name='set'),
    url(r'^remove/$', CertificateCartRemoveView.as_view(), name='remove'),
]

main/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.views.generic import TemplateView, RedirectView

# from solid_i18n.urls import solid_i18n_patterns

from apps.analytics.views import SetYMClientIDView
from apps.cart.api.views import YooKassaWebhookView, PayPalWebhookView
from apps.cart.views import CartView, CartGetDiscountView
from apps.cart.certificate.views import CertificateView
from apps.catalog.views import ProductsView, ProductView, ProductWithDiscountView
from apps.catalog.api_views import IncreaseInStockView, ChangeProductView
from apps.content.sitemap import sitemaps
from apps.content.views import HomepageView, VideoListView, VideoDetailView, PageView, robots_txt
from apps.currency.views import SetCurrencyView
from apps.lk.views import (ProfileHomeView, ProfileResetPasswordView, ProfileSetPasswordView,
                           ProfileFormView, ProfileSetPasswordFormView, MailingView)
from apps.views import PhotoUploadView


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ajax/upload/$', PhotoUploadView.as_view(), name='photo_upload'),

    url(r'^robots\.txt$', robots_txt, name='robots_txt'),
    # url(r'^robots\.txt/$', RedirectView.as_view(pattern_name='robots_txt', permanent=True)),
    url(r'^robots\.txt/$', RedirectView.as_view(pattern_name='robots_txt', permanent=False)),

    url(r'^yandex_32b44e0eb9e4fa78\.html$', TemplateView.as_view(template_name='ya_verification.html')),

    url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),

    # # api
    # url(r'^api/cart/', include('apps.cart.api.urls', namespace='cart_api')),
    # url(r'^api/certificate/', include('apps.cart.certificate.urls', namespace='certificate_api')),
    # url(r'^api/auth/', include('apps.lk.auth.urls', namespace='auth')),
    # url(r'^api/profile/edit/', ProfileFormView.as_view(), name='profile-edit'),
    # url(r'^api/forms/', include('apps.feedback.urls', namespace='forms')),
    # url(r'^api/currency/set/', SetCurrencyView.as_view(), name='set_currency'),
    url(r'^api/yookassa/webhook/', YooKassaWebhookView.as_view(), name='yookassa_webhook'),
    url(r'^api/paypal/webhook/', PayPalWebhookView.as_view(), name='paypal_webhook'),
    url(r'^api/paypal/', include('paypal.standard.ipn.urls')),

    # 3rd party apps
    # url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^admin/salmonella/', include('salmonella.urls')),
    url(r'^filer/', include('filer.urls')),
    url(r'^tinymce/', include('tinymce.urls')),

    # seo
    url(r'^sitemap\.xml$', sitemap_view, {'sitemaps': sitemaps}),
]


urlpatterns += i18n_patterns(
    # -- home --
    url(r'^$', HomepageView.as_view(), name='home'),

    # feed
    url(r'^feed/', include('apps.feed.urls', namespace='feed')),

    # -- api --
    url(r'^api/cart/', include('apps.cart.api.urls', namespace='cart_api')),
    url(r'^api/certificate/', include('apps.cart.certificate.urls', namespace='certificate_api')),
    url(r'^api/auth/', include('apps.lk.auth.urls', namespace='auth')),
    url(r'^api/profile/edit/', ProfileFormView.as_view(), name='profile-edit'),
    url(r'^api/profile/set_password/', ProfileSetPasswordFormView.as_view(), name='profile-set-password-form'),
    url(r'^api/forms/', include('apps.feedback.urls', namespace='forms')),
    url(r'^api/currency/set/', SetCurrencyView.as_view(), name='set_currency'),
    url(r'^api/analytics/client_id/', SetYMClientIDView.as_view(), name='set_ym_client_id'),
    # (admin api)
    url(r'^api/products/increase_in_stock/', IncreaseInStockView.as_view(), name='admin_increase_in_stock'),
    url(r'^api/products/change/', ChangeProductView.as_view(), name='admin_change_product'),

    # -- apps --
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/get_discount/(?P<pk>\d+)/$', CartGetDiscountView.as_view(), name='cart_get_discount'),
    url(r'^certificate/$', CertificateView.as_view(), name='certificate'),
    url(r'^profile/$', ProfileHomeView.as_view(), name='profile'),
    url(r'^profile/reset_password/(?P<signature>[^/]+)/$', ProfileResetPasswordView.as_view(), name='profile_reset_password'),
    url(r'^profile/set_password/$', ProfileSetPasswordView.as_view(), name='profile_set_password'),
    url(r'^mailing/$', MailingView.as_view(), name='mailing'),

    url(r'^women/$', ProductsView.as_view(with_category=False, sale_category=False, sex='female'), name='women'),
    url(r'^muzhskie-bikini/$', ProductsView.as_view(with_category=False, sale_category=False, sex='male'), name='men'),
    url(r'^women/specialnoe-predlogenie/$', ProductsView.as_view(with_category=False, sale_category=True, sex='female'), name='women_sale'),
    url(r'^muzhskie-bikini/specialnoe-predlogenie/$', ProductsView.as_view(with_category=False, sale_category=True, sex='male'), name='men_sale'),
    url(r'^women/(?P<slug>[^/]+)/$', ProductsView.as_view(with_category=True, sale_category=False, sex='female'), name='women_category'),
    url(r'^muzhskie-bikini/(?P<slug>[^/]+)/$', ProductsView.as_view(with_category=True, sale_category=False, sex='male'), name='men_category'),
    url(r'^women/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/$', ProductView.as_view(sex='female'), name='women_product'),
    url(r'^muzhskie-bikini/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/$', ProductView.as_view(sex='male'), name='men_product'),
    url(r'^women/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/discount/(?P<category_id>\d+)/(?P<code>[^/]+)/$',
        ProductWithDiscountView.as_view(sex='female'), name='women_product_with_discount'),
    url(r'^muzhskie-bikini/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/discount/(?P<category_id>\d+)/(?P<code>[^/]+)/$',
        ProductWithDiscountView.as_view(sex='male'), name='men_product_with_discount'),

    url(r'^video/$', VideoListView.as_view(), name='videos'),
    url(r'^video/(?P<slug>[^/]+)-(?P<pk>\d+)/$', VideoDetailView.as_view(), name='video'),

    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^contests/', include('apps.contests.urls', namespace='contests')),
    url(r'^wishlist/', include('apps.lk.wishlist.urls', namespace='wishlist')),

    url(r'^(?P<slug>[^/]+)/$', PageView.as_view(), name='page'),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cart/certificate/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.views.generic import TemplateView, FormView, View

from apps.catalog.models import Certificate
from apps.cart.cart import Cart
from apps.cart.models import DeliveryMethod, PaymentMethod
from apps.core.mixins import JSONFormMixin, JSONViewMixin
from .forms import CertificateCartItemForm


class CertificateCartSetView(JSONFormMixin, FormView):
    form_class = CertificateCartItemForm
    # template_name = 'cart/certificate.html'
    mapping = {
        'certificate': 'certificate',
        'recipient_name': 'recipient_name',
        'recipient_email': 'recipient_email',
        'sender_name': 'sender_name',
        'sender_phone': 'sender_phone',
        'sender_email': 'sender_email',
        'message': 'message',
        'date': 'date',
        'send_date': 'send_date',
    }

    def get_success_url(self, *args, **kwargs):
        return reverse('certificate')

    def form_valid(self, form):
        cart = Cart(self.request)
        cleaned_data = form.cleaned_data

        certificate_id = cleaned_data.get('certificate')
        kwargs = {}
        kwargs['send_immediately'] = not (cleaned_data.get('date') == 'on_date')
        for slug in ['recipient_name', 'recipient_email', 'sender_name', 'sender_phone',
                     'sender_email', 'message', 'send_date']:
            kwargs[slug] = cleaned_data.get(slug)

        item = cart.set_certificate(certificate_id, **kwargs)
        count = cart.count()
        summary = cart.summary()

        data = {'result': 'ok', 'count': count, 'summary': summary}
        return JsonResponse(data)


class CertificateCartRemoveView(JSONViewMixin, View):

    def post(self, request, *args, **kwargs):
        cart = Cart(request)

        # print self.DATA
        cart.remove_certificate(item_id=self.DATA.get('item_id', 0))
        count = cart.count()
        summary = cart.summary()

        data = {'result': 'ok', 'count': count, 'summary': summary}
        return JsonResponse(data)


class CertificateView(TemplateView):
    template_name = 'cart/certificate.html'

    def get_certificate(self):
        certificates = Certificate.objects.all()
        certificate = certificates.first()

        cert_id = self.request.GET.get('_certificate', 0)
        if cert_id:
            try:
                certificate = certificates.get(id=cert_id)
            except (ValueError, Certificate.DoesNotExist):
                pass

        self.certificates = certificates
        self.certificate = certificate

    def get_context_data(self, **kwargs):
        self.get_certificate()
        context = {
            'certificates': self.certificates,
            'certificate': self.certificate,
            'delivery_methods': DeliveryMethod.objects.filter(is_enabled=True),
            'payment_methods': PaymentMethod.objects.filter(is_enabled=True),
        }
        context.update(super(CertificateView, self).get_context_data(**kwargs))
        return context

apps/cart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView, View
from django.http import HttpResponseRedirect

from ..catalog.models import Attribute, GiftWrapping, SpecialOffer
from ..core.templatetags.core_tags import to_int_or_float
from ..geo.models import Country
from ..settings.models import Settings
from .cart import Cart
from .models import DeliveryMethod, PaymentMethod, CartItem, CertificateCartItem


class CartView(TemplateView):
    template_name = 'cart/cart.html'

    def get_context_data(self, **kwargs):
        self.cart = Cart(self.request)
        self.cart.cart.save() # при обновлении всегда перещитываем корзину
        cart_items = self._get_cart_items()
        certificate_items = self._get_certificate_items()
        self._color_stuff(cart_items)

        if not (cart_items.exists() or certificate_items.exists()):
            self.cart.clear()
            cart_items = CartItem.objects.none()
            certificate_items = CertificateCartItem.objects.none()

        shipping_data = {
            'country': 132,  # Россия
            'city': '',
            'postal_code': '',
            'address': '',
            'phone': '',
            'name': '',
            'email': '',
            'payment_method_id': None,
            'delivery_method_id': None,
        }
        profile = self.request.user
        if profile.is_authenticated():
            shipping_data.update(profile.shipping_data)
        _update = False
        for k, v in shipping_data.items():
            cart_obj = self.cart.cart
            # получаем shipping_data из корзины
            if getattr(cart_obj, k, None):
                shipping_data[k] = getattr(cart_obj, k)
            # если данных нет (но были в профиле) - обновляем в корзине
            elif v and hasattr(cart_obj, k):
                _k = {'country': 'country_id'}.get(k, k)
                setattr(cart_obj, _k, v)
                _update = True
        if _update:
            cart_obj.save()

        # проставляем payment_method и delivery_method

        LANGUAGE_CODE = self.request.LANGUAGE_CODE or settings.LANGUAGE_CODE
        delivery_methods = DeliveryMethod.objects.prefetch_related('payment_methods').filter(
            is_enabled=True, payment_methods__isnull=False, languages__contains=LANGUAGE_CODE,
        ).distinct()
        payment_methods = PaymentMethod.objects.prefetch_related('delivery_methods').filter(
            is_enabled=True, delivery_methods__isnull=False, languages__contains=LANGUAGE_CODE,
        ).distinct()

        _update = False
        if cart_obj.delivery_method not in delivery_methods:
            cart_obj.delivery_method = None
            shipping_data['delivery_method_id'] = None
            _update = True
        if cart_obj.payment_method not in payment_methods:
            cart_obj.payment_method = None
            shipping_data['payment_method_id'] = None
            _update = True
        if _update:
            cart_obj.save()
            
        context = {
            'cart_items': cart_items,
            'certificate_items': certificate_items,
            'with_color': self.with_color,
            'color_attribute': self.color_attribute,
            'with_gift_wrapping': True,
            'gift_wrapping_price': to_int_or_float(GiftWrapping.get_price() or 0),
            'countries': Country.objects.values('id', 'title'),
            'shipping_data': shipping_data,
            'delivery_methods': delivery_methods,
            'payment_methods': payment_methods,
            'four_products_free': Settings.objects.first().four_products_free,
        }
        context.update(super(CartView, self).get_context_data(**kwargs))
        return context

    def _get_cart_items(self):
        cart = self.cart
        cart_items = cart.cart.cartitem_set.all().select_related('product', 'option')
        for item in cart_items:
            if item.count == 0:
                item.delete()
        cart_items = cart.cart.cartitem_set.all().select_related('product', 'option')
        return cart_items.filter(product__show=True)

    def _get_certificate_items(self):
        cart = self.cart
        certificate_items = cart.cart.certificatecartitem_set.all().select_related('certificate')
        return certificate_items

    def _color_stuff(self, cart_items):
        with_color = False
        color_attribute = None

        if cart_items.exists():
            for attrs in cart_items.values_list('attrs', flat=True):
                if 'color' in attrs.keys():
                    with_color = True
                    break
            if with_color:
                color_attribute = Attribute.objects.filter(slug='color').first()
                if not color_attribute:
                    with_color = False

        self.with_color = with_color
        self.color_attribute = color_attribute


class CartGetDiscountView(View):

    def get(self, request, *args, **kwargs):
        profile = request.user
        offer_id = kwargs.get('pk')
        redirect_url = reverse('cart')

        if not profile.is_anonymous() and profile.can_get_discount:
            try:
                special_offer = SpecialOffer.get_offers().get(id=offer_id)
            except (ValueError, SpecialOffer.DoesNotExist) as e:  # noqa
                pass
            else:
                discount_code = profile.get_discount_code()
                redirect_url = special_offer.get_offer_url(discount_code=discount_code)

        return HttpResponseRedirect(redirect_url)

templates/cart/certificate.html
{% extends 'base.html' %}
{% load i18n core_tags currency_tags %}

{% block meta_title %}{{ seo_settings.certificate.get_meta_title }}{% endblock %}
{% block meta_desc %}{{ seo_settings.certificate.get_meta_desc }}{% endblock %}
{% block meta_keyw %}{{ seo_settings.certificate.get_meta_keyw }}{% endblock %}

{% block og_title %}{{ seo_settings.certificate.get_meta_title }}{% endblock %}
{% block og_desc %}{{ seo_settings.certificate.get_meta_desc }}{% endblock %}

{% block twitter_title %}{{ seo_settings.certificate.get_meta_title }}{% endblock %}
{% block twitter_desc %}{{ seo_settings.certificate.get_meta_desc }}{% endblock %}

{% block content %}
  <main>
    <div class="main_content main_cut">
      
      <ul id="touch_breadcrumb" class="breadcrumb">
        <li><a href="{% trans '#' %}">{% trans 'Главная' %}</a></li>
        <li><span>{% trans 'Подарочный сертификат' %}</span></li>
      </ul>
    
      <div id="main_content" class="wrapp_content">
        <ul class="breadcrumb">
          <li><a href="{% trans '#' %}">{% trans 'Главная' %}</a></li>
          <li><span>{% trans 'Подарочный сертификат' %}</span></li>
        </ul>
        <h1 class="title_block">{{ seo_settings.certificate.get_h1 }}</h1>
        
          <div class="table_shell table_sert">
            <div class="table_row row_sert">
              <div class="table_cell row_cell sell_sert">
                
                <div class="sertificat_block" style="background-image: url(/static/images/sertificates/bg_sertificat1.gif);">
                  <div class="sertificat_wrapp">
                    <div class="sertificat_logo">
                      <img src="/static/i/sertificat_logo.png" alt="{% trans 'Bikinimini' %}" />
                    </div>
                    <div class="sertificat_logo_name">
                      <img src="/static/i/sertificat_logo_name.png" alt="{% trans 'Anastasia Ivanovskaia' %}" />
                    </div>
                    <div class="sertificat_title">
                      {% trans 'Подарочный сертификат' %}
                    </div>
                    <div class="product_price upper_price">{{ certificate.price|to_price|with_js_certificte_price:currency|safe }}</div>
                  </div>
                </div>

                <div class="text_sert">
                  {{ seo_settings.certificate.get_seo_text|safe }}
                </div>
              </div>
              
              <div class="table_cell row_cell sell_sert_form">
                <form class="js-certificate-form" action="{% url 'certificate_api:set' %}" method="post">
                  <script>
                    (function( $ ) {
                      $.fn.selectbox2 = function() {
                      var selectDefaultHeight = 40;
                        $('#sertificates_select .selectboxssvalue').click(function() {
                          var currentHeight = $(this).closest("#sertificates_select").height();
                          if (currentHeight < 100 || currentHeight == selectDefaultHeight) {
                            $(this).closest("#sertificates_select").height("auto");
                            $(this).find('#arrow_select').attr("style", "border-radius: 1000px;transition: 0.2s;transform: rotate(180deg);");
                          }
                          if (currentHeight >= 101) {
                            $(this).closest("#sertificates_select").height(selectDefaultHeight);
                            $(this).find('#arrow_select').attr("style", "rotate(0deg);");
                          }
                        });
                        $('li.selectoption').click(function() {
                          // custom
                          var $option = $(this),
                              $select = $option.closest("#sertificates_select"),
                              t = $option.closest("li.selectoption").text(),
                              cert_id = $option.attr('data-id'),
                              price = $option.attr('data-price');

                          $select.height(selectDefaultHeight);
                          $select.find('#arrow_select').attr("style", "rotate(0deg);");
                          $select.find('.selectboxssvalue span.input_text_view').text(t);

                          $('input[name="certificate"]').val(cert_id);
                          $('.js-certificte-price').text(price);
                        });
                      };
                    })( jQuery );
                  </script>
                  <script> $(document).ready(function(){ $('#sertificates_select').selectbox2(); }); </script>

                  <input type="hidden" name="certificate" value="{{ certificate.id }}" />

                  <div class="title_normal">{% trans 'Выберите номинал' %}:<span class="orange_text">*</span></div>
                  <div class="input_shell select_shel">
                    <div class="select_img"><!--.errr-->
                      <div class="selectboxss drop_list_text" id="sertificates_select">
                        <div class="selectboxssvalue">
                          <span class="input_text_view">{{ certificate.price|to_price|currency_light:currency|safe }}</span>
                          <img src="/static/i/arrow_down_list.png" class="arrowselect" id="arrow_select" />
                        </div>
                        <ul class="selectboxssmenu">
                          {% for cert in certificates %}
                            <li class="selectoption js-select-option" data-id="{{ cert.id }}" data-price="{{ cert.price|to_price }}">{{ cert.price|to_price|currency_light:currency|safe }}</li>
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                    <span class="err_r">{% trans 'Заполните поле' %}</span>
                  </div>
                  
                  <div class="title_normal">{% trans 'Имя получателя' %}:<span class="orange_text">*</span></div>
                  <div class="input_shell">
                    <input type="text" value="" name="recipient_name" class="input_text" required placeholder="" />
                    <span class="err_r">{% trans 'Заполните поле' %}</span>
                  </div>
                  
                  <div class="title_normal">{% trans 'E-mail получателя' %}:</div>
                  <div class="input_shell">
                    <input type="email" value="" name="recipient_email" class="input_text" placeholder="" />
                    <span class="err_r">{% trans 'Заполните поле' %}</span>
                  </div>
                  
                  <div class="title_normal">{% trans 'Имя отправителя' %}:</div>
                  <div class="input_shell">
                    <input type="text" value="" name="sender_name" class="input_text" placeholder="" />
                    <span class="err_r">{% trans 'Заполните поле' %}</span>
                  </div>
                  
                  <div class="title_normal">{% trans 'Телефон отправителя' %}:<span class="orange_text">*</span></div>
                  <div class="input_shell">
                    <input type="text" value="" name="sender_phone" class="input_text" required placeholder="" />
                    <span class="err_r">{% trans 'Заполните поле' %}</span>
                  </div>
                  
                  <div class="title_normal">{% trans 'E-mail отправителя' %}:<span class="orange_text">*</span></div>
                  <div class="input_shell">
                    <input type="text" value="" name="sender_email" class="input_text" required placeholder="" />
                    <span class="err_r">{% trans 'Заполните поле' %}</span>
                  </div>
                  
                  <div class="title_normal">{% trans 'Сообщение получателю' %}:</div>
                  <div class="input_shell">
                    <textarea name="message" rows="4" id="text" class="t_area input_text bg_area"></textarea>
                    <span class="err_r">{% trans 'Заполните поле' %}</span>
                  </div>
                  
                  <div class="title_normal">{% trans 'Когда отправлять' %}:<span class="orange_text">*</span></div>
                  <div class="input_shell radio_float">
                    <label for="radio_id_1" class="radio_input">
                      <div class="input_cell">
                        <input type="radio" name="date" value="today" id="radio_id_1" class="check_radio" checked />
                      </div>
                      <p class="dott_cell"><span>{% trans 'Сейчас' %}</span></p>
                    </label>
                    
                    <label for="radio_id_2" class="radio_input">
                      <div class="input_cell">
                        <input type="radio" name="date" value="on_date" id="radio_id_2" class="check_radio" />
                      </div>
                      <p class="dott_cell"><span>{% trans 'Выбрать дату' %}</span></p>
                    </label>
                  </div>
                  
                  <div class="js-send-date-div" style="display: none;">
                    <div class="title_normal">{% trans 'Дата отправки' %}:<span class="orange_text">*</span></div>
                    <div class="input_shell">
                      <input type="text" value="{% now 'd.m.Y' %}" name="send_date" class="input_text" placeholder="" />
                      <span class="err_r">{% trans 'Заполните поле' %}</span>
                    </div>
                  </div>

                  <div class="row_form_popup row_pop_butt">
                    <button class="bt_red js-certificate-button" type="submit">{% trans 'Купить' %}</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
      </div>
      
    </div>
  </main>
{% endblock %}

{% block extra_js %}
  <script type="text/javascript">
    {% include 'js/certificate.js' %}
  </script>
{% endblock %}

templates/cart/step5_specials.html
{% load i18n core_tags currency_tags %}

{% get_random_str as random_str %}

{% if specials.count %}
  <div class="popup_row_wrapp">
    <h2 class="title_string">{% trans 'Специальное предложение <br />Только для Вас' %}!</h2>
    <h3 class="h3_pup">{% trans 'Добавьте еще одну модель' %}</h3>

    <div class="slides">
      {% for special in specials %}
        {% with special.product as sp %}
          <div class="pup_details_item js-special-offer"{% if not forloop.first %} style="display: none;"{% endif %} data-slide-id="{{ forloop.counter0 }}">
            <div class="details_item_photo">
              <div class="photo_list">
                <a href="{{ special.get_discount_url }}?code={{ random_str }}"><img style="width: 200px !important; height: 200px !important" src="{{ sp.special_offer_cover }}" alt="{{ sp.title }}"></a>
              </div>
              <abbr class="sale_details">-{{ special.discount }}%</abbr>
            </div>
            
            <div class="details_item_content">
              <h3><a href="{{ special.get_discount_url }}?code={{ random_str }}"> {{ sp.title }}</a></h3>
              <h4>{{ sp.subtitle }}</h4>
              <div class="txt_price_to">{% trans 'Цена для вас' %}:</div>
              
              <div class="product_price sale_price">{% prefix_currency currency sp.price|to_price %}<s>{{ sp.price|to_price }}</s>{% postfix_currency currency sp.price|to_price %}</div>
              <div class="product_price">{{ sp.price|with_discount:special.discount|to_price|with_currency:currency|safe }}</div>
              
              <div class="clr"></div>
              <a href="{{ special.get_discount_url }}?code={{ random_str }}" class="to_cart_list">В корзину</a>
            </div>
          </div>
        {% endwith %}
      {% endfor %}
      <div class="slides_navigation"></div>
    </div>

    <div class="pup_details_txt slides_details">
      <strong>Примечание:</strong> Скидкой можете воспользоватся только вы, 
      перейдя по ссылке с данной страницы в течение следующих двух часов.
      Если вы покинете данную страницу, скидка более не распространяется.
    </div>
    
  </div>
{% endif %}