apps/contests/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import ContestsHomeView, ContestDetailView, ParticipantDetailView, ApplyView, AddLikeView, RemoveLikeView


urlpatterns = [
    url(r'^$', ContestsHomeView.as_view(), name='home'),
    url(r'^(?P<slug>[^/]+)/$', ContestDetailView.as_view(), name='contest'),
    url(r'^(?P<contest_slug>[^/]+)/participants/(?P<pk>\d+)/$', ParticipantDetailView.as_view(), name='participant'),
    url(r'^participants/apply/$', ApplyView.as_view(), name='apply'),
    url(r'^participants/like/$', AddLikeView.as_view(), name='like'),
    url(r'^participants/dislike/$', RemoveLikeView.as_view(), name='dislike'),
]

main/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.views.generic import TemplateView, RedirectView

# from solid_i18n.urls import solid_i18n_patterns

from apps.analytics.views import SetYMClientIDView
from apps.cart.api.views import YooKassaWebhookView, PayPalWebhookView
from apps.cart.views import CartView, CartGetDiscountView
from apps.cart.certificate.views import CertificateView
from apps.catalog.views import ProductsView, ProductView, ProductWithDiscountView
from apps.catalog.api_views import IncreaseInStockView, ChangeProductView
from apps.content.sitemap import sitemaps
from apps.content.views import HomepageView, VideoListView, VideoDetailView, PageView, robots_txt
from apps.currency.views import SetCurrencyView
from apps.lk.views import (ProfileHomeView, ProfileResetPasswordView, ProfileSetPasswordView,
                           ProfileFormView, ProfileSetPasswordFormView, MailingView)
from apps.views import PhotoUploadView


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ajax/upload/$', PhotoUploadView.as_view(), name='photo_upload'),

    url(r'^robots\.txt$', robots_txt, name='robots_txt'),
    # url(r'^robots\.txt/$', RedirectView.as_view(pattern_name='robots_txt', permanent=True)),
    url(r'^robots\.txt/$', RedirectView.as_view(pattern_name='robots_txt', permanent=False)),

    url(r'^yandex_32b44e0eb9e4fa78\.html$', TemplateView.as_view(template_name='ya_verification.html')),

    url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),

    # # api
    # url(r'^api/cart/', include('apps.cart.api.urls', namespace='cart_api')),
    # url(r'^api/certificate/', include('apps.cart.certificate.urls', namespace='certificate_api')),
    # url(r'^api/auth/', include('apps.lk.auth.urls', namespace='auth')),
    # url(r'^api/profile/edit/', ProfileFormView.as_view(), name='profile-edit'),
    # url(r'^api/forms/', include('apps.feedback.urls', namespace='forms')),
    # url(r'^api/currency/set/', SetCurrencyView.as_view(), name='set_currency'),
    url(r'^api/yookassa/webhook/', YooKassaWebhookView.as_view(), name='yookassa_webhook'),
    url(r'^api/paypal/webhook/', PayPalWebhookView.as_view(), name='paypal_webhook'),
    url(r'^api/paypal/', include('paypal.standard.ipn.urls')),

    # 3rd party apps
    # url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^admin/salmonella/', include('salmonella.urls')),
    url(r'^filer/', include('filer.urls')),
    url(r'^tinymce/', include('tinymce.urls')),

    # seo
    url(r'^sitemap\.xml$', sitemap_view, {'sitemaps': sitemaps}),
]


urlpatterns += i18n_patterns(
    # -- home --
    url(r'^$', HomepageView.as_view(), name='home'),

    # feed
    url(r'^feed/', include('apps.feed.urls', namespace='feed')),

    # -- api --
    url(r'^api/cart/', include('apps.cart.api.urls', namespace='cart_api')),
    url(r'^api/certificate/', include('apps.cart.certificate.urls', namespace='certificate_api')),
    url(r'^api/auth/', include('apps.lk.auth.urls', namespace='auth')),
    url(r'^api/profile/edit/', ProfileFormView.as_view(), name='profile-edit'),
    url(r'^api/profile/set_password/', ProfileSetPasswordFormView.as_view(), name='profile-set-password-form'),
    url(r'^api/forms/', include('apps.feedback.urls', namespace='forms')),
    url(r'^api/currency/set/', SetCurrencyView.as_view(), name='set_currency'),
    url(r'^api/analytics/client_id/', SetYMClientIDView.as_view(), name='set_ym_client_id'),
    # (admin api)
    url(r'^api/products/increase_in_stock/', IncreaseInStockView.as_view(), name='admin_increase_in_stock'),
    url(r'^api/products/change/', ChangeProductView.as_view(), name='admin_change_product'),

    # -- apps --
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/get_discount/(?P<pk>\d+)/$', CartGetDiscountView.as_view(), name='cart_get_discount'),
    url(r'^certificate/$', CertificateView.as_view(), name='certificate'),
    url(r'^profile/$', ProfileHomeView.as_view(), name='profile'),
    url(r'^profile/reset_password/(?P<signature>[^/]+)/$', ProfileResetPasswordView.as_view(), name='profile_reset_password'),
    url(r'^profile/set_password/$', ProfileSetPasswordView.as_view(), name='profile_set_password'),
    url(r'^mailing/$', MailingView.as_view(), name='mailing'),

    url(r'^women/$', ProductsView.as_view(with_category=False, sale_category=False, sex='female'), name='women'),
    url(r'^muzhskie-bikini/$', ProductsView.as_view(with_category=False, sale_category=False, sex='male'), name='men'),
    url(r'^women/specialnoe-predlogenie/$', ProductsView.as_view(with_category=False, sale_category=True, sex='female'), name='women_sale'),
    url(r'^muzhskie-bikini/specialnoe-predlogenie/$', ProductsView.as_view(with_category=False, sale_category=True, sex='male'), name='men_sale'),
    url(r'^women/(?P<slug>[^/]+)/$', ProductsView.as_view(with_category=True, sale_category=False, sex='female'), name='women_category'),
    url(r'^muzhskie-bikini/(?P<slug>[^/]+)/$', ProductsView.as_view(with_category=True, sale_category=False, sex='male'), name='men_category'),
    url(r'^women/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/$', ProductView.as_view(sex='female'), name='women_product'),
    url(r'^muzhskie-bikini/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/$', ProductView.as_view(sex='male'), name='men_product'),
    url(r'^women/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/discount/(?P<category_id>\d+)/(?P<code>[^/]+)/$',
        ProductWithDiscountView.as_view(sex='female'), name='women_product_with_discount'),
    url(r'^muzhskie-bikini/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/discount/(?P<category_id>\d+)/(?P<code>[^/]+)/$',
        ProductWithDiscountView.as_view(sex='male'), name='men_product_with_discount'),

    url(r'^video/$', VideoListView.as_view(), name='videos'),
    url(r'^video/(?P<slug>[^/]+)-(?P<pk>\d+)/$', VideoDetailView.as_view(), name='video'),

    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^contests/', include('apps.contests.urls', namespace='contests')),
    url(r'^wishlist/', include('apps.lk.wishlist.urls', namespace='wishlist')),

    url(r'^(?P<slug>[^/]+)/$', PageView.as_view(), name='page'),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contests/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Contest, Participant


class ContestAdminForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ContestAdminForm, self).__init__(*args, **kwargs)
        self.fields['winner'].queryset = self.instance.participants.all()

    def clean_status(self):
        status = self.cleaned_data.get('status')
        if status == 'active':
            active_contest = Contest.objects.filter(status='active').first()
            if active_contest and (not self.instance.id or self.instance.id != active_contest.id):
                raise forms.ValidationError('Активный конкурс уже существует: {}.'.format(active_contest.title))
        return status


class ContestApplyForm(forms.ModelForm):

    class Meta:
        fields = ('contest', 'profile', 'name', 'description',)
        model = Participant

    def clean_contest(self):
        contest = self.cleaned_data.get('contest')
        if not contest.accepting_enabled:
            raise forms.ValidationError(_('Заявки на участие в конкурсе больше не принимаются.'))
        return contest

    def clean_profile(self):
        profile = self.cleaned_data.get('profile')
        contest = self.cleaned_data.get('contest')
        if contest and profile.id in contest.participants_profiles:
            raise forms.ValidationError(_('Вы уже принимаете участие в конкурсе.'))
        return profile

apps/contests/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.core.files import File
from django.http import Http404, HttpResponseRedirect, JsonResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views.generic import TemplateView, DetailView, View, CreateView
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext as __

from ..core.http_utils import get_object_from_slug_and_kwargs
from ..core.mixins import JSONFormMixin
from .forms import ContestApplyForm
from .models import Contest, Participant, ParticipantPhoto


translated_strings = (_('Фото'), _('Обязательное поле'), _('Ваш лайк засчитан'), _('Оценить участницу +'),)


class ContestsHomeView(TemplateView):
    template_name = 'contests/contests.html'

    def get_object(self, *args, **kwargs):
        contest = Contest.objects.filter(show=True, published_dt__lte=timezone.now(), status='active').first()
        return contest

    def get_context_data(self, **kwargs):
        c = self.get_object()
        another_contests = Contest.objects.filter(show=True, status='archived', published_dt__lte=timezone.now())
        if c:
            another_contests = another_contests.exclude(id=c.id)
        context = {
            'contest': c,
            'another_contests': another_contests,
        }
        context.update(super(ContestsHomeView, self).get_context_data(**kwargs))
        return context


class ContestDetailView(ContestsHomeView):
    template_name = 'contests/contest.html'

    def get_object(self, *args, **kwargs):
        kw = {'show': True, 'published_dt__lte': timezone.now()}
        contest = get_object_from_slug_and_kwargs(self.request, model=Contest, slug=self.kwargs.get('slug'), **kw)
        return contest


class ParticipantDetailView(DetailView):
    template_name = 'contests/participant.html'
    model = Participant
    context_object_name = 'participant'

    def get_object(self):
        kw = {'show': True, 'published_dt__lte': timezone.now()}
        self.contest = get_object_from_slug_and_kwargs(self.request, model=Contest, slug=self.kwargs.get('contest_slug'), **kw)
        participant = get_object_or_404(Participant, contest_id=self.contest.id, pk=self.kwargs.get('pk'))
        return participant

    def get_context_data(self, **kwargs):
        context = {
            'contest': self.contest,
        }
        context.update(super(ParticipantDetailView, self).get_context_data(**kwargs))
        return context


class ApplyView(JSONFormMixin, CreateView):
    form_class = ContestApplyForm
    mapping = {
        'contest': 'contest',
        'name': 'name',
        'description': 'description',
        'profile': 'profile',
        'photos': 'photos',
    }
    model = Participant

    def get_success_url(self):
        return self.request.path

    def get_object(self):
        return None

    def get_form(self, *args, **kwargs):
        profile = self.request.user
        if profile.is_anonymous():
            raise HttpResponseForbidden

        self.POST['profile'] = profile.id

        if hasattr(self, 'get_object'):
            form = self.form_class(self.POST, instance=self.get_object())
        else:
            form = self.form_class(self.POST)
        return form

    def form_valid(self, form):
        super(ApplyView, self).form_valid(form)
        participant = form.instance

        photos = [path for path in self.POST.get('photos', '').split(';') if path]
        for i, photo_path in enumerate(photos):
            try:
                if i == 0:
                    participant.photo.save(photo_path.split('/')[-1], File(open(photo_path[1:], 'rb')))
                    participant.save()

                photo = ParticipantPhoto.objects.create(participant=participant)
                photo.photo.save(photo_path.split('/')[-1], File(open(photo_path[1:], 'rb')))
                photo.save()
            except:
                pass

        if not participant.photo or not participant.photos.count():
            participant.delete()
            data = {'result': 'error', 'errors': [{'name': 'photos', 'label': __('Фото'),
                                                   'error_message': __('Обязательное поле')}]}
            return JsonResponse(data, status=400)

        participant = form.instance
        return JsonResponse({'result': 'ok', 'redirect_url': participant.get_absolute_url()})


class AddLikeView(View):

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            try:
                DATA = json.loads(request.body)
                participant_id = DATA['id']
                participant = get_object_or_404(Participant, id=participant_id)
                liked_participants = request.session.get('liked_participants', [])

                participant_id = str(participant_id)
                if not participant_id in liked_participants:
                    participant.likes += 1
                    participant.save()
                    liked_participants.append(participant_id)
                    request.session['liked_participants'] = liked_participants

                button_text = __('Ваш лайк засчитан')
                return JsonResponse({'result': 'ok', 'count': participant.likes_count, 'button_text': button_text})

            except (ValueError, KeyError, Participant.DoesNotExist) as e:
                err_message = '{}: {}'.format(type(e).__name__, e.message)
                return JsonResponse({'result': 'error', 'count': None, 'error': err_message}, status=400)
        else:
            raise Http404


class RemoveLikeView(View):

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            try:
                DATA = json.loads(request.body)
                participant_id = DATA['id']
                participant = get_object_or_404(Participant, id=participant_id)
                liked_participants = request.session.get('liked_participants', [])

                participant_id = str(participant_id)
                if participant_id in liked_participants:
                    participant.likes -= 1
                    participant.save()
                    liked_participants.pop(liked_participants.index(participant_id))
                    request.session['liked_participants'] = liked_participants

                button_text = __('Оценить участницу +')
                return JsonResponse({'result': 'ok', 'count': participant.likes_count, 'button_text': button_text})

            except (ValueError, KeyError, Participant.DoesNotExist) as e:
                err_message = '{}: {}'.format(type(e).__name__, e.message)
                return JsonResponse({'result': 'error', 'count': None, 'error': err_message}, status=400)
        else:
            raise Http404

templates/contests/contest.html
{% extends 'base.html' %}
{% load i18n core_tags staticfiles %}

{% block meta_title %}{{ contest.get_meta_title }}{% endblock %}
{% block meta_desc %}{{ contest.get_meta_desc }}{% endblock %}
{% block meta_keyw %}{{ contest.get_meta_keyw }}{% endblock %}

{% block og_title %}{{ contest.get_meta_title }}{% endblock %}
{% block og_desc %}{{ contest.get_meta_desc }}{% endblock %}

{% block twitter_title %}{{ contest.get_meta_title }}{% endblock %}
{% block twitter_desc %}{{ contest.get_meta_desc }}{% endblock %}

{% block content %}
  {% if contest %}
    <div class="with_banner_page banner_konkurs{% if contest.winner %} banner_konkurs_itog{% endif %}" style="background-image:url({{ contest.cover_url }});">
      <div class="with_banner_padd_page">
        {% if contest.winner %}
          <div class="with_mini_text with_makro_text">{% trans 'Победитель конкурса' %}</div>
          <div class="with_mini_text with_middle_text">{{ contest.title }}</div>
          <div class="with_big_text">{{ contest.winner.name }}</div>
          <div class="photo_list"><a href="{{ contest.winner.get_absolute_url }}"><img src="{{ contest.winner.cover_winner_url }}" alt="{{ contest.winner.name }}"></a></div>

        {% else %}
          {% if contest.title_lines.count %}
            {% for line in contest.title_lines.all %}
              <div class="{% if line.big %}with_big_text{% else %}with_mini_text{% endif %}">{{ line.line }}</div>
            {% endfor %}
          {% else %}
            <div class="with_big_text">{{ contest.title }}</div>
          {% endif %}

          {% if contest.accepting_enabled %}        
            <a href="#apply"
               data-popup-id="{% if profile.is_anonymous %}#auth{% elif profile.id in contest.participants_profiles %}#already-participating{% else %}#contest-apply{% endif %}"
               class="butt_with js-apply-button">{% trans 'Принять участие' %}</a>
          {% endif %}
        {% endif %}
        
        <div class="share_banner">
          <p>Поделиться:</p>
          <script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
          <script src="//yastatic.net/share2/share.js"></script>
          <div class="ya-share2" data-services="facebook,vkontakte,twitter,odnoklassniki,gplus" data-description="{{ contest.meta_desc }}" data-hashtags="Bikinimini.ru" data-image="{{ contest.cover_url|full_url }}" data-lang="{{ request.LANGUAGE_CODE }}"></div>
          {% comment %}
            <a href="#" class="soc_banner"><img src="/static/i/soc_face.png" alt="Поделиться в Facebook" /></a>
            <a href="#" class="soc_banner"><img src="/static/i/soc_vk.png" alt="Поделиться в ВКонтакте" /></a>
            <a href="#" class="soc_banner"><img src="/static/i/tw_icon.png" alt="Поделиться в Twitter" /></a>
            <a href="#" class="soc_banner"><img src="/static/i/soc_ok.png" alt="Поделиться в Одноклассниках" /></a>
            <a href="#" class="soc_banner"><img src="/static/i/you_icon.png" alt="Поделиться в Youtube" /></a>
            <a href="#" class="soc_banner"><img src="/static/i/soc_gplus.png" alt="Поделиться в Google Plus" /></a>
          {% endcomment %}
        </div>
      </div>
    </div>
  {% endif %}

  <main>
    <div class="main_content main_content_video">
      {% if contest and contest.show_terms %}
        <div class="blog_title"><h1 class="title_block">{% trans 'Условия конкурса' %}</h1></div>
      {% endif %}
    
      <div id="main_content" class="content_video list_push cnt_left">

        {% if contest and contest.show_terms %}
          <div class="text_preview_left txt_black">
            {{ contest.terms|safe }}
          </div>
        {% endif %}

        {% if contest and contest.participants.count %}
          <h2 class="title_block">{% trans 'Участники конкурса' %}</h2>
          <div class="item_list_wrapp item_list_wrapp_all list_face" itemscope="" itemtype="http://schema.org/ItemList">

            {% for participant in contest.participants.all %}
              <div class="product_list product_face">
                <div class="photo_list"><a href="{{ participant.get_absolute_url }}"><img src="{{ participant.cover_url }}" alt="{{ participant.name }}"></a></div>
                <h3>
                  <a href="{{ participant.get_absolute_url }}">{{ participant.name }}</a>
                  <div class="count_block js-like-parent">
                    <a href="#" class="butt_put">
                      <label for="id_like_{{ participant.id }}" class="td_label_check_win">
                        <input type="checkbox" class="js-like-participant" name="like_participant" id="id_like_{{ participant.id }}" value="1"{% if participant.id|to_str in liked_participants %} checked="checked"{% endif %} data-participant-id="{{ participant.id }}" data-like-url="{% url 'contests:like' %}" data-dislike-url="{% url 'contests:dislike' %}">
                        <img src="/static/i/heart_icon.png" alt="{% trans 'Оценить участницу' %}">
                      </label>
                    </a>
                    <span class="disc_number js-likes-count-span">{{ participant.likes_count }}</span>
                  </div>                
                </h3>
              </div>
            {% endfor %}
            
          </div>
        {% endif %}

        {% if another_contests.count %}
          <h2 class="title_block">{% trans 'Архив конкурсов' %}</h2>
          
          <div class="item_list_wrapp item_list_wrapp_all list_face arhive_list_jpg">
            {% for a_contest in another_contests %}
              <a href="{{ a_contest.get_absolute_url }}" class="product_list product_face" style="background-image:url({{ a_contest.list_cover_url }});">
                <div class="txt_product">
                  <p><strong>{% trans 'Конкурс' %}</strong></p>
                  <h2>{{ a_contest.title }}</h2>
                  <p>{{ a_contest.published_dt|date:'d.m.Y' }}</p>
                </div>
              </a>
            {% endfor %}
          </div>
        {% endif %}

      </div>

    </div>
  </main>
{% endblock %}

{% block popups %}
  <div style="display: none">
    <a rel="leanModal1" href="#error-popup"></a>
    <a rel="leanModal1" href="#already-participating"></a>
    <a rel="leanModal1" href="#contest-apply"></a>
  </div>

  <div class="window_popup no_float mini_window_popup callback_form" id="error-popup" style="display:none;">
      <div class="close_popup call_close js-call-close"><img src="/static/i/close_white_45.png" alt="{% trans 'Закрыть' %}"></div>
      <div class="wrap_window_popup bg_wrapp_window">
          <div class="popup_row">
              <div class="popup_row_wrapp">
                  <h3 class="popup_title" style="margin-bottom: 10px;">{% trans 'При отправке формы произошла ошибка' %}:</h3>
                  <p class="call_introtext popup_text"></p>
                  {% comment %}
                  <div class="red_bor_butt">
                      <span class="js-call-close usual_link">{% trans 'Закрыть' %}</span>
                  </div>
                  {% endcomment %}
                  <div class="bt_req_call red_bor_butt js-call-close">
                    <button class="butt_border">{% trans 'Закрыть' %}</button>
                  </div>
              </div>
          </div>
      </div>
  </div>

  <div class="window_popup no_float mini_window_popup callback_form" id="already-participating" style="display:none;">
      <div class="close_popup call_close js-call-close"><img src="/static/i/close_white_45.png" alt="{% trans 'Закрыть' %}"></div>
      <div class="wrap_window_popup bg_wrapp_window">
          <div class="popup_row">
              <div class="popup_row_wrapp">
                  <h3 class="popup_title" style="margin-bottom: 10px;">{% trans 'Ошибка' %}:</h3>
                  <p class="call_introtext popup_text">{% trans 'Вы уже принимаете участие в конкурсе' %}.</p>
                  <div class="bt_req_call red_bor_butt js-call-close">
                    <button class="butt_border">{% trans 'Закрыть' %}</button>
                  </div>
              </div>
          </div>
      </div>
  </div>

  {% if contest.accepting_enabled %}
    <div class="window_popup no_float" id="contest-apply" style="display:none;">
      <div class="close_popup js-call-close"><img src="/static/i/close_icon.png" alt="{% trans 'Закрыть' %}" /></div>
      <div class="wrap_window_popup bg_wrapp_window">
        <div class="popup_row">
          <div class="popup_row_wrapp">
            <h2 class="title_popup">{% trans 'Принять участие в конкурсе' %} "{{ contest.title }}"</h2>
            <form class="js-apply-form dropzone" id="loadingFiles" action="{% url 'contests:apply' %}" method="post" enctype="multipart/form-data">
              <input type="hidden" name="contest" value="{{ contest.id }}">
              <div class="error-messages"></div>

              <div class="rows_popup_input">
                <label class="lbl_box">
                  <p>Имя:<span class="orange_text">*</span></p>
                  <input required type="text" style="padding-left: 15px;" value="{% if profile.is_authenticated and profile.name %}{{ profile.name }}{% endif %}" name="name" class="input_text" />
                </label>
              </div>

              <br/>
              <div class="rows_popup_input">
                <label class="lbl_box">
                  <p>Описание:</p>
                  <textarea name="description" class="input_text no_hover_border" style="padding: 12px 2.25% 0; width: 95.45%; height: 135px;"></textarea>
                </label>
              </div>            

              <div class="rows_popup_input dz-clickable dropzone-div" style="margin: 20px 0 30px;">
                <label class="lbl_box">
                  <p>Фото:<span class="orange_text">*</span></p>
                  <div class="download">
                    <div class="download_ttl"><b>{% trans 'Перетащите сюда файлы или' %} <a class="open-file dz-message" href="javascript:void(0);">{% trans 'выберите на компьютере' %}</a></b></div>
                    <div class="download_text">{% trans 'Максимальный размер фото - 10МБ. Не более 5 фотографий' %}.</div>
                    <div class="dropzone-previews"></div>
                    <input type="hidden" name="photos">
                  </div>
                </label>
              </div>

              <div class="row_form_popup row_pop_butt">
                <button class="bt_red" type="submit">{% trans 'Принять участие' %}</button>
              </div>
            </form>
          </div>
        </div>
        
        
      </div>
    </div>
  {% endif %}
{% endblock %}

{% block extra_css %}
  <link href="/static/dropzone-custom.css" type="text/css"  rel="stylesheet" />
  {# <link href="/static/dropzone-demo.css" type="text/css"  rel="stylesheet" /> #}
{% endblock %}

{% block extra_js %}
  <script src="{% static 'js/dropzone-custom.js' %}"></script>
  {# <script src="{% static 'js/dropzone.js' %}"></script> #}
  <script>
    {% include 'contests/include/dropzone.js' %}
  </script>
  <script type="text/javascript">
    {% include 'contests/include/contests.js' %}
  </script>
{% endblock %}

templates/contests/contests.html
{% extends 'contests/contest.html' %}

{% block meta_title %}{{ seo_settings.contests.get_meta_title }}{% endblock %}
{% block meta_desc %}{{ seo_settings.contests.get_meta_desc }}{% endblock %}
{% block meta_keyw %}{{ seo_settings.contests.get_meta_keyw }}{% endblock %}

{% block og_title %}{{ seo_settings.contests.get_meta_title }}{% endblock %}
{% block og_desc %}{{ seo_settings.contests.get_meta_desc }}{% endblock %}

{% block twitter_title %}{{ seo_settings.contests.get_meta_title }}{% endblock %}
{% block twitter_desc %}{{ seo_settings.contests.get_meta_desc }}{% endblock %}