apps/cart/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .paypal_views import paypal_form
from .views import (Step0View, Step2View, Step3View, UpdateCartView, CartAjaxView,
                    YooKassaWebhookView, YooKassaCartView, PayPalWebhookView, PayPalCartView, RoboKassaCartView, RoboKassaSuccessView, RoboKassaFailView)


urlpatterns = [
    url(r'^steps/0/$', Step0View.as_view(), name='step0'),
    url(r'^steps/2/$', Step2View.as_view(), name='step2'),
    url(r'^steps/3/$', Step3View.as_view(), name='step3'),

    url(r'^update/$', UpdateCartView.as_view(), name='update'),

    url(r'^set/$', CartAjaxView.as_view(action='set'), name='set'),
    url(r'^remove/$', CartAjaxView.as_view(action='remove'), name='remove'),
    url(r'^clear/$', CartAjaxView.as_view(action='clear'), name='clear'),

    # yookassa
    url(r'^yookassa/webhook/$', YooKassaWebhookView.as_view(), name='yookassa_webhook'),
    url(r'^yookassa/(?P<pk>\d+)/$', YooKassaCartView.as_view(), name='yookassa'),

    # paypal
    url(r'^paypal/webhook/$', PayPalWebhookView.as_view(), name='paypal_webhook'),
    url(r'^paypal/(?P<pk>\d+)/$', PayPalCartView.as_view(), name='paypal'),
    url(r'^paypal/form/$', paypal_form, name='paypal_form'),

    # robokassa
    url(r'^robokassa/result/$', RoboKassaCartView.as_view(), name='robokassa'),
    url(r'^robokassa/success/$', RoboKassaSuccessView.as_view(), name='robokassa_success'),
    url(r'^robokassa/fail/$', RoboKassaFailView.as_view(), name='robokassa_fail'),

]

apps/lk/wishlist/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import WishListView, WishListAddView, WishListRemoveView


urlpatterns = [
    url(r'^$', WishListView.as_view(), name='home'),
    url(r'^add/$', WishListAddView.as_view(), name='add'),
    url(r'^remove/$', WishListRemoveView.as_view(), name='remove'),
]

main/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.views.generic import TemplateView, RedirectView

# from solid_i18n.urls import solid_i18n_patterns

from apps.analytics.views import SetYMClientIDView
from apps.cart.api.views import YooKassaWebhookView, PayPalWebhookView
from apps.cart.views import CartView, CartGetDiscountView
from apps.cart.certificate.views import CertificateView
from apps.catalog.views import ProductsView, ProductView, ProductWithDiscountView
from apps.catalog.api_views import IncreaseInStockView, ChangeProductView
from apps.content.sitemap import sitemaps
from apps.content.views import HomepageView, VideoListView, VideoDetailView, PageView, robots_txt
from apps.currency.views import SetCurrencyView
from apps.lk.views import (ProfileHomeView, ProfileResetPasswordView, ProfileSetPasswordView,
                           ProfileFormView, ProfileSetPasswordFormView, MailingView)
from apps.views import PhotoUploadView


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ajax/upload/$', PhotoUploadView.as_view(), name='photo_upload'),

    url(r'^robots\.txt$', robots_txt, name='robots_txt'),
    # url(r'^robots\.txt/$', RedirectView.as_view(pattern_name='robots_txt', permanent=True)),
    url(r'^robots\.txt/$', RedirectView.as_view(pattern_name='robots_txt', permanent=False)),

    url(r'^yandex_32b44e0eb9e4fa78\.html$', TemplateView.as_view(template_name='ya_verification.html')),

    url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),

    # # api
    # url(r'^api/cart/', include('apps.cart.api.urls', namespace='cart_api')),
    # url(r'^api/certificate/', include('apps.cart.certificate.urls', namespace='certificate_api')),
    # url(r'^api/auth/', include('apps.lk.auth.urls', namespace='auth')),
    # url(r'^api/profile/edit/', ProfileFormView.as_view(), name='profile-edit'),
    # url(r'^api/forms/', include('apps.feedback.urls', namespace='forms')),
    # url(r'^api/currency/set/', SetCurrencyView.as_view(), name='set_currency'),
    url(r'^api/yookassa/webhook/', YooKassaWebhookView.as_view(), name='yookassa_webhook'),
    url(r'^api/paypal/webhook/', PayPalWebhookView.as_view(), name='paypal_webhook'),
    url(r'^api/paypal/', include('paypal.standard.ipn.urls')),

    # 3rd party apps
    # url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^admin/salmonella/', include('salmonella.urls')),
    url(r'^filer/', include('filer.urls')),
    url(r'^tinymce/', include('tinymce.urls')),

    # seo
    url(r'^sitemap\.xml$', sitemap_view, {'sitemaps': sitemaps}),
]


urlpatterns += i18n_patterns(
    # -- home --
    url(r'^$', HomepageView.as_view(), name='home'),

    # feed
    url(r'^feed/', include('apps.feed.urls', namespace='feed')),

    # -- api --
    url(r'^api/cart/', include('apps.cart.api.urls', namespace='cart_api')),
    url(r'^api/certificate/', include('apps.cart.certificate.urls', namespace='certificate_api')),
    url(r'^api/auth/', include('apps.lk.auth.urls', namespace='auth')),
    url(r'^api/profile/edit/', ProfileFormView.as_view(), name='profile-edit'),
    url(r'^api/profile/set_password/', ProfileSetPasswordFormView.as_view(), name='profile-set-password-form'),
    url(r'^api/forms/', include('apps.feedback.urls', namespace='forms')),
    url(r'^api/currency/set/', SetCurrencyView.as_view(), name='set_currency'),
    url(r'^api/analytics/client_id/', SetYMClientIDView.as_view(), name='set_ym_client_id'),
    # (admin api)
    url(r'^api/products/increase_in_stock/', IncreaseInStockView.as_view(), name='admin_increase_in_stock'),
    url(r'^api/products/change/', ChangeProductView.as_view(), name='admin_change_product'),

    # -- apps --
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/get_discount/(?P<pk>\d+)/$', CartGetDiscountView.as_view(), name='cart_get_discount'),
    url(r'^certificate/$', CertificateView.as_view(), name='certificate'),
    url(r'^profile/$', ProfileHomeView.as_view(), name='profile'),
    url(r'^profile/reset_password/(?P<signature>[^/]+)/$', ProfileResetPasswordView.as_view(), name='profile_reset_password'),
    url(r'^profile/set_password/$', ProfileSetPasswordView.as_view(), name='profile_set_password'),
    url(r'^mailing/$', MailingView.as_view(), name='mailing'),

    url(r'^women/$', ProductsView.as_view(with_category=False, sale_category=False, sex='female'), name='women'),
    url(r'^muzhskie-bikini/$', ProductsView.as_view(with_category=False, sale_category=False, sex='male'), name='men'),
    url(r'^women/specialnoe-predlogenie/$', ProductsView.as_view(with_category=False, sale_category=True, sex='female'), name='women_sale'),
    url(r'^muzhskie-bikini/specialnoe-predlogenie/$', ProductsView.as_view(with_category=False, sale_category=True, sex='male'), name='men_sale'),
    url(r'^women/(?P<slug>[^/]+)/$', ProductsView.as_view(with_category=True, sale_category=False, sex='female'), name='women_category'),
    url(r'^muzhskie-bikini/(?P<slug>[^/]+)/$', ProductsView.as_view(with_category=True, sale_category=False, sex='male'), name='men_category'),
    url(r'^women/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/$', ProductView.as_view(sex='female'), name='women_product'),
    url(r'^muzhskie-bikini/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/$', ProductView.as_view(sex='male'), name='men_product'),
    url(r'^women/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/discount/(?P<category_id>\d+)/(?P<code>[^/]+)/$',
        ProductWithDiscountView.as_view(sex='female'), name='women_product_with_discount'),
    url(r'^muzhskie-bikini/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/discount/(?P<category_id>\d+)/(?P<code>[^/]+)/$',
        ProductWithDiscountView.as_view(sex='male'), name='men_product_with_discount'),

    url(r'^video/$', VideoListView.as_view(), name='videos'),
    url(r'^video/(?P<slug>[^/]+)-(?P<pk>\d+)/$', VideoDetailView.as_view(), name='video'),

    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^contests/', include('apps.contests.urls', namespace='contests')),
    url(r'^wishlist/', include('apps.lk.wishlist.urls', namespace='wishlist')),

    url(r'^(?P<slug>[^/]+)/$', PageView.as_view(), name='page'),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/lk/wishlist/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.db.utils import IntegrityError
from django.http import Http404, JsonResponse
from django.views.generic import View, TemplateView
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext as __

from apps.catalog.models import AttributeOption, Product, ProductOption
from apps.core.mixins import JSONViewMixin
from apps.hash_utils import make_hash_from_cartitem
from apps.lk.models import WishListItem
from .utils import get_wishlist_from_request, get_wishlist_item_prices


translated_strings = (_('Неправильный формат запроса'), _('Неправильный id товара'),)


class WishListView(TemplateView):
    template_names = {
        'default': 'wishlist/wishlist.html',
        'ajax': 'wishlist/include/wishlist.html',
    }

    def get_template_names(self, *args, **kwargs):
        return (self.template_names['ajax'] if self.request.is_ajax()
                else self.template_names['default'])

    def get(self, request, *args, **kwargs):
        response = super(WishListView, self).get(request, *args, **kwargs)
        if request.is_ajax():
            html = response.rendered_content
            response = JsonResponse({'result': 'ok', 'html': html})
            response['Cache-Control'] = 'no-cache, no-store'
        return response

    def get_wishlist(self):
        profile = self.request.user
        wishlist = get_wishlist_from_request(self.request)
        products = {}
        product_options = {}
        options = {}

        # wishlist = self.get_default()

        if len(wishlist):
            product_ids = [item['product_id'] for item in wishlist]
            product_options_ids = [item['option_id'] for item in wishlist]
            options_ids = [item['attrs'].values() for item in wishlist]
            options_ids = set([el for lst in options_ids for el in lst])

            products = {p.id: p for p in Product.objects.filter(id__in=product_ids)}
            product_options = {o.id: o for o in ProductOption.objects.filter(id__in=product_options_ids)}
            options = {o.id: o for o in AttributeOption.objects.select_related('attribute').filter(id__in=options_ids)}
            wishlist = [item for item in wishlist
                        if item['product_id'] in products.keys()
                        and item.get('option_id') in product_options.keys()]

        self.wishlist = wishlist
        self.products = products
        self.product_options = product_options
        self.options = options

    def get_context_data(self, **kwargs):
        self.get_wishlist()
        context = {
            'wishlist': self.wishlist,
            'products': self.products,
            'product_options': self.product_options,
            'options': self.options,
        }
        context.update(super(WishListView, self).get_context_data(**kwargs))
        return context

    def get_default(self):
        wishlist = []
        for p in Product.objects.all().prefetch_related('options'):
            option = p.options.first()
            item = {
                'product_id': p.id,
                'option_id': option.id,
                'attrs': {k: v[0] for k, v in option.attrs.items()},
                'extra_products': {},
                'price': float(option.price),
            }
            item['hash'] = make_hash_from_cartitem(item['attrs'], item['extra_products'])
            wishlist.append(item)
        self.request.session['wishlist'] = wishlist
        return wishlist


class WishListAddView(JSONViewMixin, View):

    def post(self, request, *args, **kwargs):
        DATA = self.DATA
        profile = request.user

        try:
            product_id = int(DATA['product_id'])
            option_id = int(DATA['option_id'])
            attrs = DATA.get('attrs', {})
            extra_products = DATA.get('extra_products', {})
        except ValueError:
            data = {'result': 'error', 'error': __('Неправильный формат запроса')}
            return JsonResponse(data, status=400)

        hash = make_hash_from_cartitem(attrs, extra_products)
        wishlist = get_wishlist_from_request(self.request)
        # product_ids = [item['product_id'] for item in wishlist]
        # product_options_ids = [item['option_id'] for item in wishlist]

        # print hash

        if profile.is_anonymous():
            the_item = None

            for item in wishlist:
                # if item['product_id'] == product_id:
                if item['product_id'] == product_id and item['hash'] == hash:
                    the_item = item

            if the_item is None:
                the_item = {}
                wishlist.append(the_item)

            prices = get_wishlist_item_prices(product_id, option_id, extra_products)
            price_rub = prices['rub']
            price_eur = prices['eur']
            price_usd = prices['usd']

            the_item.update({
                'product_id': product_id,
                'option_id': option_id,
                'price_rub': float(price_rub),
                'price_eur': float(price_eur),
                'price_usd': float(price_usd),
                'attrs': attrs,
                'extra_products': extra_products,
                'hash': hash,
            })
            request.session['wishlist'] = wishlist

        else:
            try:
                kwargs = {'profile_id': profile.id, 'product_id': product_id, 'hash': hash}
                the_item = WishListItem.objects.filter(**kwargs).first()
                if not the_item:
                    the_item = WishListItem(option_id=option_id, **kwargs)
                the_item.option_id = option_id
                the_item.attrs = attrs
                the_item.extra_products = extra_products
                the_item.save()
            except IntegrityError:
                data = {'result': 'error', 'error': __('Неправильный id товара')}
                return JsonResponse(data, status=400)

        wishlist = get_wishlist_from_request(self.request)
        data = {'result': 'ok', 'wishlist_count': len(wishlist)}
        return JsonResponse(data)


class WishListRemoveView(JSONViewMixin, View):

    def post(self, request, *args, **kwargs):
        DATA = self.DATA
        profile = request.user

        try:
            product_id = int(DATA['product_id'])
            attrs = DATA.get('attrs', {})
            extra_products = DATA.get('extra_products', {})
        except ValueError:
            data = {'result': 'error', 'error': __('Неправильный формат запроса')}
            return JsonResponse(data, status=400)

        hash = make_hash_from_cartitem(attrs, extra_products)
        wishlist = get_wishlist_from_request(self.request)
        product_ids = [item['product_id'] for item in wishlist]

        if product_id in product_ids:
            if profile.is_anonymous():
                for i, item in enumerate(wishlist):
                    if item['product_id'] == product_id and item['hash'] == hash:
                        wishlist.pop(i)
                        break
                request.session['wishlist'] = wishlist

            else:
                try:
                    the_item = WishListItem.objects.filter(profile_id=profile.id, product_id=product_id, hash=hash).first()
                    if the_item:
                        the_item.delete()
                except IntegrityError:
                    data = {'result': 'error', 'error': __('Неправильный id товара')}
                    return JsonResponse(data, status=400)

        wishlist = get_wishlist_from_request(self.request)
        data = {'result': 'ok', 'wishlist_count': len(wishlist)}
        return JsonResponse(data)

templates/wishlist/popup.html
{% load i18n %}
{# <div class="window_popup no_float mini_window_popup" id="wishlist" style="display:none;"> #}
<div class="window_popup rows_order_block item_list_popup" id="wishlist" style="display:none;">
  <div class="close_popup js-call-close"><img src="/static/i/close_icon.png" alt="Закрыть" /></div>
  <div class="wrap_window_popup bg_wrapp_window">
    <div class="popup_row">
      <div class="popup_row_wrapp">
        <div class="rows_cut_block">
          
          <div class="rows_block_info">
            <div class="row_info">
              <h2 class="title_block">{% trans "Список желаемых покупок" %} </h2>
            </div>
            
            <div class="js-wishlist-popup-content"></div>
          </div>
          
        </div>
      </div>
    </div>
    
  </div>
</div>

templates/wishlist/wishlist.html
{% extends 'base.html' %}
{% load i18n core_tags catalog_tags wishlist_tags currency_tags %}

{% block meta_title %}{{ seo_settings.wishlist.get_meta_title }}{% endblock %}
{% block meta_desc %}{{ seo_settings.wishlist.get_meta_desc }}{% endblock %}
{% block meta_keyw %}{{ seo_settings.wishlist.get_meta_keyw }}{% endblock %}

{% block og_title %}{{ seo_settings.wishlist.get_meta_title }}{% endblock %}
{% block og_desc %}{{ seo_settings.wishlist.get_meta_desc }}{% endblock %}

{% block twitter_title %}{{ seo_settings.wishlist.get_meta_title }}{% endblock %}
{% block twitter_desc %}{{ seo_settings.wishlist.get_meta_desc }}{% endblock %}

{% block content %}
  <main>
    <div class="main_content main_content_video">
      
      <div class="blog_title">
        <ul class="breadcrumb">
          <li><a href="{% url 'home' %}">{% trans "Главная" %}</a></li>
          <li><span>{% trans "Список желаемых покупок" %}</span></li>
        </ul>
        <h1 class="title_block">{% trans "Список желаемых покупок" %}</h1>
      </div>
      
      <div id="main_content" class="content_video list_push">
        {% if wishlist|length %}
          <div class="item_list_wrapp item_list_wrapp_all" itemscope="" itemtype="http://schema.org/ItemList">
            {% for item in wishlist %}
              {% get_product item.product_id as product %}
              {% get_product_option item.option_id as product_option %}
              {% get_product_attrs_url product item.attrs item.extra_products as product_url %}

              {% if product and product_option %}
                <form class="js-product-form" method="post" action="{% url 'cart_api:set' %}" style="display: inline-block;">
                  {% csrf_token %}
                  <input type="hidden" name="product_id" value="{{ product.id }}">
                  <div class="product_list product_list_all" style="height: auto; overflow: visible;">
                    <div class="photo_list">
                      <a href="{{ product_url }}">
                        <img src="{{ product.cover_thumb }}" alt="{{ product.title }}">
                      </a>
                      {% if product.is_on_sale %}<span class="product-label product-label_discount" title="">-{{ product.sale_percent }}%</span>{% endif %}
                      {% if product.installment %}
                      <span class="product-label_installment product-label_discount" title="">Рассрочка</span>
                      {% endif %}
                    </div>
                    <h3>
                      <a href="{{ product_url }}">{{ product.title }}</a>
                      <div class="sec_block_item">
                        <a href="#" class="butt_put">
                          <label for="put_item{{ forloop.counter }}" class="td_label_check_win">
                            <input type="checkbox" name="put_item" id="put_item{{ forloop.counter }}" value="1" checked="checked"
                                   class="js-wishlist-input"
                                   data-add-url="{% url 'wishlist:add' %}" data-remove-url="{% url 'wishlist:remove' %}"
                                   data-product-id="{{ item.product_id }}" data-option-id="{{ item.option_id }}"
                                   data-price="{{ item.price }}"
                                   data-attrs='{{ item.attrs|to_json|safe }}'
                                   data-extra-products='{{ item.extra_products|to_json|safe }}' />
                            <img src="/static/i/heart_icon.png" style="cursor: pointer !important;" alt="Отложить">
                          </label>
                        </a>
                        
                        <a href="{{ product_url }}" class="sett_butt">
                          <img src="/static/i/sett_icon.png" alt="Изменить комплектацию" title="Изменить комплектацию">
                        </a>
                      </div>
                    </h3>
                    
                    <h4>{% if product.subtitle %}{{ product.subtitle }}{% endif %}</h4>
                    
                    <ul class="settings_item">
                      {% get_attrs_options item.attrs.items as attrs_options %}
                      {% for option in attrs_options.size %}
                        <li><span>{{ option.attribute.title }}:</span><strong>{{ option.title }}</strong></li>
                      {% endfor %}
                      {% for option in attrs_options.color %}
                        {% if option.picture %}
                          <li class="last_color"><span>{{ option.attribute.title }}:</span><div class="td_color_box" style="background: url('{{ option.picture_url }}'); border: 1px solid #ccc;" title="{{ option.title }}">{{ option.title }}</div></li>
                        {% else %}
                          <li class="last_color"><span>{{ option.attribute.title }}:</span><div class="td_color_box" style="background-color:{{ option.color }}; border: 1px solid #ccc;" title="{{ option.title }}">{{ option.title }}</div></li>
                        {% endif %}
                      {% endfor %}
                    </ul>

                    {% if item.price is not None %}
                      <div class="product_price{% if product.is_on_sale %} product_price_sale{% endif %}">
                        {% if product.is_on_sale %}
                          <s title="Старая цена">{{ item.price|to_price|with_currency:currency|abbr_to_span|safe }}</s>
                          {{ item.price|to_sale_price:product.sale_percent|with_currency:currency|abbr_to_span|safe }}
                        {% else %}
                          {{ item.price|to_price|with_currency:currency|abbr_to_span|safe }}
                        {% endif %}
                      </div>
                    {% endif %}
                    {% if product_option.in_stock %}
                      <button class="js-wishlist-cart-button to_cart_list" data-type="add" type="submit">{% trans "В корзину" %}</button>
                    {% else %}
                      <button class="js-wishlist-cart-button to_cart_list" data-type="order" type="submit">{% trans "Под заказ" %}</button>
                    {% endif %}
                  </div>
                </form>
              {% endif %}
            {% endfor %}
          </div>
        {% else %}
          <h3 style="margin-bottom: 250px;">{% trans "Товаров в списке желаемых покупок нет" %}. <a href="{% url 'women' %}">{% trans "Вернуться в каталог" %}</a></h3>
        {% endif %}
      </div>
      
    </div>
  </main>
{% endblock %}