apps/lk/auth/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url, include

from .views import LoginView, LogoutView, RegistrationView, ResetPasswordView


urlpatterns = [
    url(r'^social/', include('apps.lk.auth.social.urls', namespace='social')),

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),
    url(r'^reset_password/$', ResetPasswordView.as_view(), name='reset_password'),
]

main/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.views.generic import TemplateView, RedirectView

# from solid_i18n.urls import solid_i18n_patterns

from apps.analytics.views import SetYMClientIDView
from apps.cart.api.views import YooKassaWebhookView, PayPalWebhookView
from apps.cart.views import CartView, CartGetDiscountView
from apps.cart.certificate.views import CertificateView
from apps.catalog.views import ProductsView, ProductView, ProductWithDiscountView
from apps.catalog.api_views import IncreaseInStockView, ChangeProductView
from apps.content.sitemap import sitemaps
from apps.content.views import HomepageView, VideoListView, VideoDetailView, PageView, robots_txt
from apps.currency.views import SetCurrencyView
from apps.lk.views import (ProfileHomeView, ProfileResetPasswordView, ProfileSetPasswordView,
                           ProfileFormView, ProfileSetPasswordFormView, MailingView)
from apps.views import PhotoUploadView


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ajax/upload/$', PhotoUploadView.as_view(), name='photo_upload'),

    url(r'^robots\.txt$', robots_txt, name='robots_txt'),
    # url(r'^robots\.txt/$', RedirectView.as_view(pattern_name='robots_txt', permanent=True)),
    url(r'^robots\.txt/$', RedirectView.as_view(pattern_name='robots_txt', permanent=False)),

    url(r'^yandex_32b44e0eb9e4fa78\.html$', TemplateView.as_view(template_name='ya_verification.html')),

    url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),

    # # api
    # url(r'^api/cart/', include('apps.cart.api.urls', namespace='cart_api')),
    # url(r'^api/certificate/', include('apps.cart.certificate.urls', namespace='certificate_api')),
    # url(r'^api/auth/', include('apps.lk.auth.urls', namespace='auth')),
    # url(r'^api/profile/edit/', ProfileFormView.as_view(), name='profile-edit'),
    # url(r'^api/forms/', include('apps.feedback.urls', namespace='forms')),
    # url(r'^api/currency/set/', SetCurrencyView.as_view(), name='set_currency'),
    url(r'^api/yookassa/webhook/', YooKassaWebhookView.as_view(), name='yookassa_webhook'),
    url(r'^api/paypal/webhook/', PayPalWebhookView.as_view(), name='paypal_webhook'),
    url(r'^api/paypal/', include('paypal.standard.ipn.urls')),

    # 3rd party apps
    # url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^admin/salmonella/', include('salmonella.urls')),
    url(r'^filer/', include('filer.urls')),
    url(r'^tinymce/', include('tinymce.urls')),

    # seo
    url(r'^sitemap\.xml$', sitemap_view, {'sitemaps': sitemaps}),
]


urlpatterns += i18n_patterns(
    # -- home --
    url(r'^$', HomepageView.as_view(), name='home'),

    # feed
    url(r'^feed/', include('apps.feed.urls', namespace='feed')),

    # -- api --
    url(r'^api/cart/', include('apps.cart.api.urls', namespace='cart_api')),
    url(r'^api/certificate/', include('apps.cart.certificate.urls', namespace='certificate_api')),
    url(r'^api/auth/', include('apps.lk.auth.urls', namespace='auth')),
    url(r'^api/profile/edit/', ProfileFormView.as_view(), name='profile-edit'),
    url(r'^api/profile/set_password/', ProfileSetPasswordFormView.as_view(), name='profile-set-password-form'),
    url(r'^api/forms/', include('apps.feedback.urls', namespace='forms')),
    url(r'^api/currency/set/', SetCurrencyView.as_view(), name='set_currency'),
    url(r'^api/analytics/client_id/', SetYMClientIDView.as_view(), name='set_ym_client_id'),
    # (admin api)
    url(r'^api/products/increase_in_stock/', IncreaseInStockView.as_view(), name='admin_increase_in_stock'),
    url(r'^api/products/change/', ChangeProductView.as_view(), name='admin_change_product'),

    # -- apps --
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/get_discount/(?P<pk>\d+)/$', CartGetDiscountView.as_view(), name='cart_get_discount'),
    url(r'^certificate/$', CertificateView.as_view(), name='certificate'),
    url(r'^profile/$', ProfileHomeView.as_view(), name='profile'),
    url(r'^profile/reset_password/(?P<signature>[^/]+)/$', ProfileResetPasswordView.as_view(), name='profile_reset_password'),
    url(r'^profile/set_password/$', ProfileSetPasswordView.as_view(), name='profile_set_password'),
    url(r'^mailing/$', MailingView.as_view(), name='mailing'),

    url(r'^women/$', ProductsView.as_view(with_category=False, sale_category=False, sex='female'), name='women'),
    url(r'^muzhskie-bikini/$', ProductsView.as_view(with_category=False, sale_category=False, sex='male'), name='men'),
    url(r'^women/specialnoe-predlogenie/$', ProductsView.as_view(with_category=False, sale_category=True, sex='female'), name='women_sale'),
    url(r'^muzhskie-bikini/specialnoe-predlogenie/$', ProductsView.as_view(with_category=False, sale_category=True, sex='male'), name='men_sale'),
    url(r'^women/(?P<slug>[^/]+)/$', ProductsView.as_view(with_category=True, sale_category=False, sex='female'), name='women_category'),
    url(r'^muzhskie-bikini/(?P<slug>[^/]+)/$', ProductsView.as_view(with_category=True, sale_category=False, sex='male'), name='men_category'),
    url(r'^women/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/$', ProductView.as_view(sex='female'), name='women_product'),
    url(r'^muzhskie-bikini/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/$', ProductView.as_view(sex='male'), name='men_product'),
    url(r'^women/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/discount/(?P<category_id>\d+)/(?P<code>[^/]+)/$',
        ProductWithDiscountView.as_view(sex='female'), name='women_product_with_discount'),
    url(r'^muzhskie-bikini/(?P<category_slug>[^/]+)/(?P<slug>[^/]+)-(?P<pk>\d+)/discount/(?P<category_id>\d+)/(?P<code>[^/]+)/$',
        ProductWithDiscountView.as_view(sex='male'), name='men_product_with_discount'),

    url(r'^video/$', VideoListView.as_view(), name='videos'),
    url(r'^video/(?P<slug>[^/]+)-(?P<pk>\d+)/$', VideoDetailView.as_view(), name='video'),

    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^contests/', include('apps.contests.urls', namespace='contests')),
    url(r'^wishlist/', include('apps.lk.wishlist.urls', namespace='wishlist')),

    url(r'^(?P<slug>[^/]+)/$', PageView.as_view(), name='page'),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/blocks/currency_change.html
{% load i18n %}

<div class="block_curr_down"{% if currency_change_style %} style="{{ currency_change_style }}"{% endif %}>
  {% trans 'Цена в' as transDefaultLabel %}
  <span class="title_down_block">{{ currency_change_label|default:transDefaultLabel }}: </span>
  <script>
    (function( $ ) {
      $.fn.selectbox = function() {
      //var selectDefaultHeight = $('.selectboxss').height();
      var selectDefaultHeight = 40;
        $('.selectboxss .selectboxssvalue').click(function() {
          var currentHeight = $(this).closest(".selectboxss").height();
          if (currentHeight < 100 || currentHeight == selectDefaultHeight) {
            $(this).closest(".selectboxss").height("auto");
            $(this).find('.arrowselect').attr("style", "border-radius: 1000px;transition: 0.2s;transform: rotate(180deg);");
          }
          if (currentHeight >= 101) {
            $(this).closest(".selectboxss").height(selectDefaultHeight);
            $(this).find('.arrowselect').attr("style", "rotate(0deg);");
          }
        });
        $('li.selectoption').click(function() {
          var $li = $(this);
          $li.closest(".selectboxss").height(selectDefaultHeight);
          $li.closest(".selectboxss").find('.arrowselect').attr("style", "rotate(0deg);");
          
          var t = $li.closest("li.selectoption").text();
          $li.closest(".selectboxss").find('.selectboxssvalue img.input_mage').attr('src', t);

          // custom
          var currency = $li.attr('data-currency'),
              $form = $('form.js-set-currency-form');

          console.log('woo');
          $form.find('input[name="currency"]').val(currency);
          $form.submit();
        });
      };
    })( jQuery );
  </script>
  <script> $(document).ready(function(){ $('.selectboxss').selectbox(); }); </script>
  <div class="select_img">
    <div class="selectboxss">
      <div class="selectboxssvalue">
        <img src="/static/i/{{ currency }}_img.png" class="input_mage" />
        <img src="/static/i/arrow_down_list.png" class="arrowselect" />
      </div>
      <ul class="selectboxssmenu js-currency-ul" data-current-currency="{{ currency }}">
        <li class="selectoption js-currency-li" data-currency="rub" style="background-image:url(/static/i/rub_img.png);"><span>/static/i/rub_img.png</span></li>
        <li class="selectoption js-currency-li" data-currency="eur" style="background-image:url(/static/i/eur_img.png);"><span>/static/i/eur_img.png</span></li>
        <li class="selectoption js-currency-li" data-currency="usd" style="background-image:url(/static/i/usd_img.png);"><span>/static/i/usd_img.png</span></li>
      </ul>
      <form style="display: none;" class="js-set-currency-form" method="post" action="{% url 'set_currency' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.build_absolute_uri }}">
        <input type="hidden" name="currency" value="">
      </form>
    </div>
  </div>
</div>

templates/blocks/footer.html
{% load core_tags %}
{% load i18n %}

<footer>
  <div class="footer_wrapp">
    <ul class="menu_foot">
      <li class="logo_foot"><a href=""><img src="/static/i/logo.png" alt="{% trans 'МиниБикини' %}" /></a></li>
    </ul>
    
    <div id="foot_menu">
      <a href="#" id="touch-menu-foot">Меню</a>
      <ul>
        {% for item in menu.footer %}
          <li><a href="{{ item.link }}" title="{{ item.label }}">{{ item.label }}</a></li>
        {% endfor %}
      </ul>
    </div>
    
    <ul class="menu_foot contacts_foot">
      <li class="bt_phone"><a href="tel:{{ settings.phone|to_phone }}">{{ settings.phone|safe }}</strong></a></li>
      <li class="bt_soc"><a href="tg://resolve?domain={{ settings.telegram_login|to_telegram }}"><img src="/static/i/icons8-телеграм.svg" alt="{% trans '' %}"></a></li>
      <li class="bt_soc"><a href="whatsapp://send?phone={{ settings.whatsapp_phone|to_phone }}"><img src="/static/i/icons8-whatsapp.svg" alt="{% trans '' %}" /></a></li>
      <!-- <li class="bt_soc"><a href="{{ settings.instagram }}"><img src="/static/i/inst.png" alt="{% trans 'Instagram' %}" /></a></li> -->
	  <li class="bt_soc"><a href="https://www.instagram.com/bikini_mini_ivanovskaya"><img src="/static/i/icons8-instagram-48.svg" alt="{% trans 'Instagram' %}" /></a></li>
      <li class="bt_req_call"><a rel="leanModal1" name="callback" href="#callback"{% if ENABLE_METRICS and settings.ym_code %} onclick="yaCounter{{ YM_COUNTER }}.reachGoal('button_callback'); return true;"{% endif %}><strong>{% trans 'Обратный звонок' %}</strong></a></li>
    </ul>
  </div>
</footer>


<!-- высота карточек в каталоге и на всём сайте >>> -->
	<script type="text/javascript" src="/static/js/query.matchHeight.js"></script>
	<script type="text/javascript">
		(function() {
			$(function() {
				var byRow = $('div').hasClass('shell_wrapp');
				$('div.item_list_wrapp').each(function() {
					$(this).children('div.product_list').matchHeight({
						byRow: byRow
					});
				});
			});
		})();
	</script>
<!-- высота карточек в каталоге и на всём сайте <<< -->


<!--callback >>> -->
<div class="window_popup no_float mini_window_popup callback_form" id="callback" style="display:none;">
    <div class="close_popup call_close js-call-close"><img src="/static/i/close_white_45.png" alt="{% trans 'Закрыть' %}"></div>
    <div class="wrap_window_popup bg_wrapp_window">
        <div class="popup_row">
            <div class="popup_row_wrapp">
                <h2>{% trans 'Заказать звонок' %}</h2>
                <p class="call_introtext">{% trans 'Заполните форму, и мы вам перезвоним' %}.</p>
                <div class="row_form_popup">
                    <form class="callBackForm js-usual-form" method="post" action="{% url 'forms:callback' %}">
                        {% csrf_token %}
                        <div class="error-messages"></div>
                        <label for="callback_id_name">
                            <span>{% trans 'Ваше имя' %}:</span>
                            <input type="text" value="{{ profile.name|default_if_none:'' }}" name="name" required id="callback_id_name" class="input_text" />
                        </label>
                        <label for="callback_id_phone">
                            <span>{% trans 'Телефон' %}:</span>
                            <input type="text" value="{{ profile.phone|default_if_none:'' }}" name="phone" required id="callback_id_phone" class="input_text" />
                        </label>
                        <div class="bt_req_call red_bor_butt">
                            <button class="butt_border">{% trans 'Заказать звонок' %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% comment %}
<div class="window_popup" id="auth" style="display: none;">
  <div class="close_popup js-call-close"><img src="/static/i/close_icon.png" alt="Закрыть"></div>
  <div class="wrap_window_popup bg_wrapp_window">
    <div class="popup_row">
      <div class="popup_row_wrapp">
        <h2 class="title_popup">{% trans 'Я уже являюсь <br>клиентом BIKINIMINI' %}</h2>

        <form class="js-auth-form js-auth-login-form" action="{% url 'auth:login' %}" method="post">
          <div class="error-messages"></div>

          <div class="row_form_popup">
            <label class="lbl_box">
              <p>{% trans 'Ваш e-mail' %}</p>
              <input type="email" required="required" value="" name="email" class="input_text">
            </label>
          </div>
          
          <div class="row_form_popup">
            <label class="lbl_box">
              <p>{% trans 'Ваш пароль' %}</p>
              <input type="password" required="required" value="" name="password" class="input_text">
            </label>
          </div>
          
          <div class="row_form_popup">
            <label class="lbl_box check_popup_row">
              <input class="check_form" type="checkbox" name="remember_me">
              <p>{% trans 'Запомнить меня на сайте' %}</p>
            </label>
          </div>
          
          <div class="row_form_popup row_pop_butt">
            <button class="bt_red">{% trans 'Войти' %}</button>
            <span class="js-show-popup" data-popup-id="#reset_password">{% trans 'Забыли пароль?' %}</span>
            <a rel="leanModal1" style="display: none;" name="reset_password" href="#reset_password">{% trans 'Забыли пароль?' %}</a>
          </div>
          
          <div class="row_form_popup">
            <p>{% trans 'Войти при помощи соц. сетей' %}:</p>
            <div class="soc_enter">
              <a href="{% url 'auth:social:fb' %}"><img src="/static/i/soc_face.png" alt="{% trans 'Facebook' %}"></a>
              <a href="{% url 'auth:social:vk' %}"><img src="/static/i/soc_vk.png" alt="{% trans 'ВКонтакте' %}"></a>
              <a href="{% url 'auth:social:gp' %}"><img src="/static/i/soc_gplus.png" alt="{% trans 'Google Plus' %}"></a>
              <a href="{% url 'auth:social:ig' %}"><img src="/static/i/soc_ins.png" alt="{% trans 'Instagram' %}"></a>
            </div>
          </div>

        </form>

      </div>
    </div>
    
    <div class="or_block">{% trans 'или' %}</div>
    
    <div class="popup_row bg_popup">
      <div class="popup_row_wrapp">
        <h2 class="title_popup">{% trans 'Я новый <br>клиент BIKINIMINI' %}</h2>

        <form class="js-auth-form js-auth-registration-form" action="{% url 'auth:registration' %}" method="post">
          <div class="error-messages"></div>

          <div class="row_form_popup">
            <label class="lbl_box">
              <p>{% trans 'Ваш e-mail' %}</p>
              <input type="email" required="required" value="" name="email" class="input_text">
            </label>
          </div>
          
          <div class="row_form_popup">
            <label class="lbl_box">
              <p>{% trans 'Ваш пароль' %}</p>
              <input type="password" required="required" value="" name="password" class="input_text">
            </label>
          </div>
          
          <div class="row_form_popup">
            <label class="lbl_box">
              <p>{% trans 'Ваш пароль ещё раз' %}</p>
              <input type="password" required="required" value="" name="password_repeat" class="input_text">
            </label>
          </div>
          
          <div class="row_form_popup">
            <label class="lbl_box">
              <p>{% trans 'ФИО' %}</p>
              <input type="text" required="required" value="" name="name" class="input_text">
            </label>
          </div>

          <div class="row_form_popup">
            <label class="lbl_box check_popup_row">
              <input class="check_form" type="checkbox" name="subscription" style="margin-right: 5px;">
              <p style="float: none;">{% trans 'Я хочу получать информацию о скидках и новинках' %}</p>
            </label>
          </div>

          <div class="row_form_popup row_pop_butt">
            <button class="bt_red">{% trans 'Далее' %}</button>
          </div>
        </form>
        
      </div>
    </div>
    
  </div>
</div>
{% endcomment %}


<div class="window_popup_reg no_float mini_window_popup callback_form" id="reset_password" style="display:none;">
    <div class="close_popup call_close js-call-close"><img src="/static/i/close_white_45.png" alt="{% trans 'Закрыть' %}"></div>
    <div class="wrap_window_popup bg_wrapp_window">
        <div class="popup_row_reg">
            <div class="popup_row_wrapp">
                <h2>{% trans 'Восстановить пароль' %}</h2>
                {# <p class="call_introtext">{% trans 'Введите свой email, через который вы регистрировались на сайте' %}.</p> #}
                <div class="row_form_popup">
                    <form class="callBackForm js-usual-form" method="post" action="{% url 'auth:reset_password' %}">
                        {% csrf_token %}
                        <div class="error-messages"></div>
                        <label for="reset_password_id_email">
                            <span>{% trans 'Ваш email' %}:</span>
                            <input type="email" value="" name="email" required id="reset_password_id_email" class="input_text" />
                        </label>
                        <div class="bt_req_call red_bor_butt">
                            <button class="butt_border">{% trans 'Отправить' %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% block popups %}{% endblock %}

<script type="text/javascript" src="/static/js/modal.js"></script>
<script type="text/javascript">
	$(function() {
		$('a[rel*=leanModal1]').leanModal({ top : 200, closeButton: ".js-call-close" });
	});
</script>
<!--callback <<< -->

templates/blocks/header_menu.html
{% load i18n core_tags %}
{% get_current_language as CURRENT_LANGUAGE %}
{% get_current_path as CURRENT_PATH %}
{% get_translated_path as TRANSLATED_PATH %}

<div id="touch_menu">
  <div class="lang_head lng_header">
    <a href="#" onclick="return false;" class="lang_head_tit">{% trans 'Язык' %}: {{ LANGUAGES_DICT|get_value:CURRENT_LANGUAGE|slice:':2'|upper }}<img src="/static/i/blank.gif" onclick="nodeExpand(19860001,0)" id="img_19860001"></a>
    <ul id="tb_19860001" style="display: none;">
      {% for lang_code, lang_name in LANGUAGES|slice:":2" %}
        <form action="{% url 'set_language' %}" method="post" id="i18n_{{ lang_code }}1">
          {% csrf_token %}
          <input name="next" type="hidden" value="{% get_translated_path lang=lang_code %}" />
          <input name="language" type="hidden" value="{{ lang_code }}" />
        </form>
        <li>{% if CURRENT_LANGUAGE == lang_code %}<img src="/static/i/arrow_list.png">{{ lang_name }}{% else %}<a href="#" onClick="document.getElementById('i18n_{{ lang_code }}1').submit()">{{ lang_name }}</a>{% endif %}</li>
      {% endfor %}
    </ul>
  </div>
  
  <div id="logo_mini"><a href="{% url 'home' %}" title="{% trans 'МиниБикини' %}"><img src="/static/i/logo.png" alt="{% trans 'МиниБикини' %}" /></a></div>
  <a href="#" id="touch-menu-top">Меню</a>
</div>

<div class="menu_top_line_wrapp">
  <div class="logo"><a href="{% url 'home' %}" title="{% trans 'МиниБикини' %}"><img src="/static/i/logo.png" alt="{% trans 'МиниБикини' %}" /></a></div>
  
  <ul class="cat_row_top">
    <li><a href="{% url 'women' %}" title="{% trans 'Женщинам' %}">{% trans 'Женщинам' %}</a></li>
    <li><a href="{% url 'men' %}" title="{% trans 'Мужчинам' %}">{% trans 'Мужчинам' %}</a></li>
  </ul>
  
  <ul class="cat_row_top cat_row_top2">
    {% for item in menu.header %}
      <li><a href="{{ item.link }}" title="{{ item.label }}">{{ item.label }}</a></li>
    {% endfor %}
  </ul>
  <div class="clr clr_mrgn"></div>
  <div class="list_top_menu_wrapp">
    <ul class="list_menu_lev1">
      <li><a href="{% url 'certificate' %}">{% trans 'Подарочный сертификат' %}</a></li>
      {% comment %} <li><a href="{% url 'blog:home' %}"><img src="/static/i/logo_mini.png" alt="desinger" />{% trans 'desinger' %}</a></li> {% endcomment %}
      <!--<li><a href="{% url 'videos' %}">{% trans 'Видео' %}</a></li>-->
      <li><a href="{% url 'wishlist:home' %}" class="js-show-wishlist-button">{% trans 'Список желаемых покупок' %}&nbsp;&nbsp;<img src="/static/i/desir.png" alt="" />&nbsp;&nbsp;<span class="disc_number js-wishlist-count">{{ wishlist|length }}</span></a></li>
    </ul>
    <div style="display: none"><a rel="leanModal1" href="#wishlist"></a></div>
    <ul class="list_menu_lev1 list_menu_lev2 js-header-menu">
      <li class="lang_head">
        <a href="#" onclick="return false;" class="lang_head_tit">{% trans 'Язык' %}: {{ LANGUAGES_DICT|get_value:CURRENT_LANGUAGE|slice:':3'|upper }}<img src="/static/i/blank.gif" onClick="nodeExpand(198600,0)"  id="img_198600"></a>
        
        <ul id="tb_198600" style="display:none">
          {% for lang_code, lang_name in LANGUAGES|slice:":2" %}
            <form action="{% url 'set_language' %}" method="post" id="i18n_{{ lang_code }}">
              {% csrf_token %}
              <input name="next" type="hidden" value="{% get_translated_path lang=lang_code %}" />
              <input name="language" type="hidden" value="{{ lang_code }}" />
            </form>
            <li>{% if CURRENT_LANGUAGE == lang_code %}<img src="/static/i/arrow_list.png">{{ lang_name }}{% else %}<a href="#" onClick="document.getElementById('i18n_{{ lang_code }}').submit()">{{ lang_name }}</a>{% endif %}</li>
          {% endfor %}
        </ul>
      </li>

      <script type="text/javascript">
        function nodeExpand(nodeId, level) {
          var d = document;
          var img = 'img_' + nodeId;
          var tb = 'tb_' + nodeId;
          if(d.getElementById(tb).style.display == 'none') {
            if(level == 0) {d.getElementById(img).src = '/static/i/blank.gif';}
            if(level == 1) {d.getElementById(img).src = '/static/i/blank.gif';}
            d.getElementById(tb).style.display = '';
          }
          else {
            if(level == 0) {d.getElementById(img).src = '/static/i/blank.gif';}
            if(level == 1) {d.getElementById(img).src = '/static/i/blank.gif';}
            d.getElementById(tb).style.display = 'none';
          }
        }
      </script>
      <li class="js-auth-switch"{% if not profile.is_anonymous %} style="display: none;"{% endif %}><a rel="leanModal1" href="#auth" href="#">{% trans 'Вход / регистрация' %}</a></li>
      <li class="js-auth-switch"{% if profile.is_anonymous %} style="display: none;"{% endif %}><a href="{% url 'profile' %}">{% trans 'Мой профиль' %}</a></li>
      <li class="js-auth-switch"{% if profile.is_anonymous %} style="display: none;"{% endif %}><a href="{% url 'profile' %}?tab=orders">{% trans 'История покупок' %}</a></li>
      <li class="js-auth-switch"{% if profile.is_anonymous %} style="display: none;"{% endif %}><a href="{% url 'auth:logout' %}">{% trans 'Выход' %}</a></li>
    </ul>
  </div>
</div>

templates/blocks/paypal_form.html
{{ form.render }}